homeassistant:
  # Name of the location where Home Assistant is running
  name: Esparina Residences
  # Location required to calculate the time the sun rises and sets
  latitude: 1.381885
  longitude: 103.891475
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp
 # Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
#sensor:
#  - platform: mitemp_bt
#    rounding: False
#    period: 30
#    log_spikes: False
#    use_median: False
#    active_scan: False
    #    hci_interface: 0
    #    encryptors:
    #               'A4:C1:38:7C:B9:D8': '38feac4bef85e17090a835f03398443a'
    #    whitelist: False
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

cast:
  media_player:
    - host: 192.168.1.128

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    key: 'iwdmrawcbloqwjtd'

light:
  - platform: group
    name: Dining Lights
    entities:
      - light.yeelight_color_0x7e1b81f
      - light.yeelight_color_0x7de2eab

switch:
  - platform: broadlink
    host: 192.168.1.71
    mac: '78:0F:77:18:02:B1'
    switches:
      hall_aircon:
        friendly_name: "Hall AirCon"
        #        command_on: 'JgBMAm86DCwQKQ8ODg4MEQwsDBEODRApDCwQDQwsDw4MEQwrECkPDgwsDyoPDg4ODykPDg8NDykPDg8ODg4PDQ8ODg4PDRANDw4ODg8NDw4MEA8ODg4PDQ0QDg4PDg4ODykNEA8NDBAPDg8ODioPKQwRDw0MEA8qDykPKgwRDg4PDg4ODw0PDg8pDykPDg8pDSwMEQwQDBEMLA8NDRAPDgwQDykPDgwQDw4PDg4ODBAPDgwRDg4MEA8ODg4PDQ8ODg4PDQ8ODg4MEQwQDQ8PDg8ODg0PDgwRDg0QDQwQDw4PDQwQDw4PDQ0QDw0PDg4ODw0PDg8NDw4MEA8NDRAPDQ8NDRAMEA4PDBAODw4ODw4NDw4ODRAODg0QDSsNLAwQDRAMLA4rDAACMHQ6DyoMLA0PDRAPDQ8qDg4PDg4qDyoPDQ8pDw4PDQ0sDykNEA4qDyoODg0QDykPDQ0QDCwNEAwQDRAMEA0QDBAPDg4ODw4ODgwRDg4ODg8ODg4PDg4ODw0PDgwQDSwODg0QDg4ODg8ODCwOKw4ODBAPDgwsDSsNLAwQDRAODwwQDBEMEA0rDSwNEAwsDSsNEAwQDRAMLA0QDBAMEA0QDSsNEAwQDRAMEA0PDRAMEA0PDRAMEA0QDBANEAwQDRAMEA0QDBAODw0PDRAMEA0QDBANEAwQDQ8NEAwQDBAODwwQDRAMEA0PDRANDw0QDBANDw4PDQ8NEA0PDQ8NEA0PDRAMEA0PDg8NDw0PDRAMEA0QDQ8NEA0PDSsOKwwQDg8NKw4rDQANBQAAAAAAAAAAAAAAAA=='
        command_on: 'JgBMAnE4DioPKg8ODg4ODw4qDg8ODg8pDisODw0qEA0ODw8pDyoODw4qDykPDg8ODSsPDg0PDykPDg4PDg0PDg4PDw0PDg4ODw4ODg8NDg4PDg4PDQ8PDg4ODg4ODw4ODykPDg4ODw4ODg4PDykOKg8ODg8ODg4PDioODw4qDw4ODw4ODg4PDg4qDioPDg4qDyoPDg8NDykQDQ8pDw4PDg0PDykPDg4PDg4PDQ8ODg4PDg4ODg4ODw4ODg8PDQ8ODg4PDQ8ODQ8PDg4ODg4ODw4ODg8NDw8ODQ8ODg8ODg4PDg4ODw0ODw4ODw4NDw8NDg8ODg4PDg4ODw4ODw4ODg8NDg8ODg8ODQ8PDg8NDg8NDw8NDw4ODg4qDw4ODw4qDg8NKw8pDwACLnY4DioQKQ4PEA0ODg8pDg8PDQ8qDioODw8pDw4ODw8pDykPDw0rDioQDQ4PDioPDg4ODykPDg4PDQ8PDQ4PDg4PDg8NDw4ODg8NDw4ODg8ODQ8ODg4PDg4PDg4OECgQDQ4ODw4PDQ4PDykPKQ8ODw4ODg4ODykPDg8pDg8ODw4ODw4ODg8pDykQDQ4qDyoPDg8NDykPDg8pDw4ODw0PDykODw4ODw4NDw8ODg4ODg8ODQ8PDQ4PDg4PDg8NDw4ODg8NDg8ODg8NDg8ODg8ODQ8ODw4ODg8NDw8NDw4ODg8ODQ8PDQ8ODg4ODw0PDg4ODw4ODg8ODg8ODg4ODg8ODg4PDg0PDw0PDg4ODg8ODg8ODg4ODw0rDw0ODw4qDw4NKw8pDgANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgBMAm86DSwPKQ8ODw0NEA8qDBAPDg4qDSwPDQ0sDg4NEAwsDSwPDgwsDSwPDg4ODyoODg8ODioPDgwQDRAODg8ODg4NEA4ODw4ODg8NDw4MEA8ODBANEAwQDw4ODg8ODw0PDgwRDBAPDg4ODykPKg0QDg4PDg0rDw4PKQ0QDRAODgwRDBAPDQ8qDC0ODg0sDioPDg4ODw4PDQ8ODw0PDg0PDyoMEA8ODg4PKg8NDRAPDQ8ODg4PDg4ODw0NEA8NDRAPDQ8ODBANEA8NDw4ODg0QDg4NEAwQDw4ODg4PDBANEA4ODw4ODg8ODg4PDQ0QDg4PDg4ODw4ODg8NDw4ODg0QDBAPDgwQDw4ODg0QDw0PDg4ODw0PDg8NDyoPKg4ODCwPDg8qDgACL3Q7DioPKgwQDw4MEA8qDw0PDg8qDioPDg4qDw4MEA8qDykNEA8qDioPDg4ODyoMEA8ODCwNEA8NDw4PDQ0QDg4PDRANDw4PDQ8ODg4NDw8ODw0PDg4ODw4ODg0QDg4PDQ0QDw0PDg4ODSwPKQ8ODw0PDg8pDRAPKhAMDRAMEA8ODg4PDg8pDyoNDw8qDSwNDw8ODw0PDg4ODw4ODg8ODioPDg8NDRAPKQ0QDQ8PDg8NDRAPDg4ODw4MEA0QDg4NEA4ODw4ODg8NEA0NEA4ODw4ODg8NDRAMEA0QDw0NEA0QDg4PDg4ODw0NEA8NDw4ODw4ODw4ODg8NDw4MEA0QDw4ODg8ODBAPDg8NDw4ODg8NDw4PDQ8ODioNLA0QDioNEAwsDwANBQAAAAAAAAAAAAAAAA=='
      master_bedroom_aircon:
        friendly_name: "Master Bedroom Aircon"
        command_on: 'JgBMAnE4DioPKg8ODg4ODw4qDg8ODg8pDisODw0qEA0ODw8pDyoODw4qDykPDg8ODSsPDg0PDykPDg4PDg0PDg4PDw0PDg4ODw4ODg8NDg4PDg4PDQ8PDg4ODg4ODw4ODykPDg4ODw4ODg4PDykOKg8ODg8ODg4PDioODw4qDw4ODw4ODg4PDg4qDioPDg4qDyoPDg8NDykQDQ8pDw4PDg0PDykPDg4PDg4PDQ8ODg4PDg4ODg4ODw4ODg8PDQ8ODg4PDQ8ODQ8PDg4ODg4ODw4ODg8NDw8ODQ8ODg8ODg4PDg4ODw0ODw4ODw4NDw8NDg8ODg4PDg4ODw4ODw4ODg8NDg8ODg8ODQ8PDg8NDg8NDw8NDw4ODg4qDw4ODw4qDg8NKw8pDwACLnY4DioQKQ4PEA0ODg8pDg8PDQ8qDioODw8pDw4ODw8pDykPDw0rDioQDQ4PDioPDg4ODykPDg4PDQ8PDQ4PDg4PDg8NDw4ODg8NDw4ODg8ODQ8ODg4PDg4PDg4OECgQDQ4ODw4PDQ4PDykPKQ8ODw4ODg4ODykPDg8pDg8ODw4ODw4ODg8pDykQDQ4qDyoPDg8NDykPDg8pDw4ODw0PDykODw4ODw4NDw8ODg4ODg8ODQ8PDQ4PDg4PDg8NDw4ODg8NDg8ODg8NDg8ODg8ODQ8ODw4ODg8NDw8NDw4ODg8ODQ8PDQ8ODg4ODw0PDg4ODw4ODg8ODg8ODg4ODg8ODg4PDg0PDw0PDg4ODg8ODg8ODg4ODw0rDw0ODw4qDw4NKw8pDgANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgBMAm86DSwPKQ8ODw0NEA8qDBAPDg4qDSwPDQ0sDg4NEAwsDSwPDgwsDSwPDg4ODyoODg8ODioPDgwQDRAODg8ODg4NEA4ODw4ODg8NDw4MEA8ODBANEAwQDw4ODg8ODw0PDgwRDBAPDg4ODykPKg0QDg4PDg0rDw4PKQ0QDRAODgwRDBAPDQ8qDC0ODg0sDioPDg4ODw4PDQ8ODw0PDg0PDyoMEA8ODg4PKg8NDRAPDQ8ODg4PDg4ODw0NEA8NDRAPDQ8ODBANEA8NDw4ODg0QDg4NEAwQDw4ODg4PDBANEA4ODw4ODg8ODg4PDQ0QDg4PDg4ODw4ODg8NDw4ODg0QDBAPDgwQDw4ODg0QDw0PDg4ODw0PDg8NDyoPKg4ODCwPDg8qDgACL3Q7DioPKgwQDw4MEA8qDw0PDg8qDioPDg4qDw4MEA8qDykNEA8qDioPDg4ODyoMEA8ODCwNEA8NDw4PDQ0QDg4PDRANDw4PDQ8ODg4NDw8ODw0PDg4ODw4ODg0QDg4PDQ0QDw0PDg4ODSwPKQ8ODw0PDg8pDRAPKhAMDRAMEA8ODg4PDg8pDyoNDw8qDSwNDw8ODw0PDg4ODw4ODg8ODioPDg8NDRAPKQ0QDQ8PDg8NDRAPDg4ODw4MEA0QDg4NEA4ODw4ODg8NEA0NEA4ODw4ODg8NDRAMEA0QDw0NEA0QDg4PDg4ODw0NEA8NDw4ODw4ODw4ODg8NDw4MEA0QDw4ODg8ODBAPDg8NDw4ODg8NDw4PDQ8ODioNLA0QDioNEAwsDwANBQAAAAAAAAAAAAAAAA=='
      master_bedroom_light:
        friendly_name: "Master Bedroom Light"
        command_on: 'sQCMAAYNCiQhDSINIQ0hDSEOIQ0hDSENCyQhDSENCiUhDQolIQ4LAAFoIQ0hDSINIQ0hDSINCiQiDAsjIg0hDSINIQ0hDSEOIQ0hDQskIQ0hDQsjIg0KJCIOCgABaCIMIg0hDSENIg0hDQokIgwLJCEOIQ0hDSENIQ0iDSENIQ0KJSENIQ0KJSENCiUhAAXcAAAAAAAAAAAAAAAA'
        command_off: 'sQCMAAYNCiQhDSINIQ0hDSEOIQ0hDSENCyQhDSENCiUhDQolIQ4LAAFoIQ0hDSINIQ0hDSINCiQiDAsjIg0hDSINIQ0hDSEOIQ0hDQskIQ0hDQsjIg0KJCIOCgABaCIMIg0hDSENIg0hDQokIgwLJCEOIQ0hDSENIQ0iDSENIQ0KJSENIQ0KJSENCiUhAAXcAAAAAAAAAAAAAAAA'
      master_bedroom_fan:
        friendly_name: "Master Bedroom Fan"
        #command_on: 'sgg0AAsAAWkiDiINIg0iDiINIg0LJSIOCyUiDSINIg4iDiINIg0iDiIOCyUiDSIOCyULJSINCyYAAAAA'
        #command_on: 'smo0AAwAAWgkDCMNIwwjDSMMIwwMJCMMDCQjDCMNIwwjDCMNIwwjDSMNDCMjDCMMIw0MJAwkDCUAAAAA'
        command_on: 'shU0AAwAAWgjDSMNIw0iDSMNIg0LJCMNCyQjDSMNIg0jDSMNIg0jDSMNCyUjDSINIg0MJAslDCYAAAAA'
        command_off: 'sgY0AAwAAWgjDSMNIw0jDSMNIw0MJCMNDCQjDSMNIw0jDSMNIw0jDSMNDCQjDSMNIw0jDQwkDCUAAAAA'
      hall_light:
        friendly_name: "Hall Light"
        command_on: 'sgCSAAwOIA0LJCENCiUJJSENCiQhDiENIQ0KJQokIQ0KJSAOCiQhDQokIg4KAAFoIQ0hDSENIQ0iDCINCiQhDQolCiQhDgokIQ0hDSIMCiUKJCEOCiQiDAsjIg0KJCEPCgABaCEMIg0hDSENIQ4gDgokIQ0KJQokIQ0KJSENIQ0hDgklCiUgDQskIQ0KJSENCiUgAAXcAAAAAAAA'
        command_off: 'sgCSAAwOIA0LJCENCiUJJSENCiQhDiENIQ0KJQokIQ0KJSAOCiQhDQokIg4KAAFoIQ0hDSENIQ0iDCINCiQhDQolCiQhDgokIQ0hDSIMCiUKJCEOCiQiDAsjIg0KJCEPCgABaCEMIg0hDSENIQ4gDgokIQ0KJQokIQ0KJSENIQ0hDgklCiUgDQskIQ0KJSENCiUgAAXcAAAAAAAA'
      hall_fan:
        friendly_name: "Hall Fan"
        command_on: 'sgCYAAUKCQQEBA4FBAQkCyMiDQokISEIBAQNEAYLDQokCiQZCA4EBzcPFyUKJCENCyULAAFnIQ0hDSENIQ0iDCINCiQhDQokCyQiDAsjIgwiDSIMCyQKJCIMCyQhDQokCyQhDQomCgABZyENIQ0hDSIMIg0hDQokIQ0LJAokIgwLJCENIQ0iDAskCiQhDQskIQ0KJAskIQ0KAAXc'
        command_off: 'sgY0AAwAAWciDSMNIw0jDSMNIw0MJCMNDCQMJCMNCyQiDSMNIw0LJAwkIw0LJCINIw0iDQskCyYAAAAA'

google_assistant:
  project_id: home-assistant-228714
  service_account: !include service_account.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - group
  entity_config:
    light.gateway_light_7c49ebb0b94a:
      name: gateway
      room: Master Bedroom
    switch.master_bedroom_aircon:
      name: aircon
      room: Master Bedroom
    switch.master_bedroom_fan:
      name: fan
      room: Master Bedroom

logger:
  default: warn
  logs:
    custom_components.mitemp_bt: info
