hello_world:
  module: hello
  class: HelloWorld
#common_toilet_light:
#  module: common_toilet_light
#  class: CommonToiletLight
dining_room_light:
  module: motion_door_triggered_light
  class: MotionDoorTriggeredLight
  door: binary_sensor.door_window_sensor_158d00027b02f9
  light: light.dining_lights
  sensor: binary_sensor.motion_sensor_158d0002583b24
  motion_state: off
master_room_light:
  module: motion_door_triggered_light
  class: MotionDoorTriggeredLight
  door: binary_sensor.door_window_sensor_158d000276dab0
  light: switch.master_bedroom_light
  sensor: binary_sensor.motion_sensor_158d0001ae95f0
  motion_state: off
common_walkway_light:
  module: common_walkway_light
  class: CommonWalkwayLight
dining_light_switch:
  module: wireless_switch
  class: WirelessSwitch
  switch: binary_sensor.switch_158d0001e82307
  single_click_entity: light.dining_lights
  double_click_entity: switch.hall_light
master_bedroom_switch:
  module: wireless_switch
  class: WirelessSwitch
  switch: binary_sensor.switch_158d0001e82285
  single_click_entity: switch.master_bedroom_light
  double_click_entity: switch.master_bedroom_fan
